# Generated by Django 5.1.7 on 2025-03-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
