# Generated by Django 5.1.7 on 2025-03-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_admin_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayOfficials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('term_start', models.DateField()),
                ('term_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('O', 'Ongoing'), ('C', 'Completed'), ('U', 'Upcoming')], max_length=1)),
                ('project_picture', models.ImageField(upload_to='project_pics/')),
            ],
        ),
    ]
