# Generated by Django 5.1.7 on 2025-03-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_barangayofficials_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangayofficials',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
    ]
