# Generated by Django 5.1.7 on 2025-03-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_barangayofficials_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_picture', models.ImageField(upload_to='resident_pics/')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('birthdate', models.DateField()),
                ('birth_place', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('contact_number', models.CharField(max_length=11)),
                ('status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], max_length=1)),
                ('is_male', models.BooleanField()),
                ('is_employed', models.BooleanField()),
                ('is_voters', models.BooleanField()),
                ('religion', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
