# Generated by Django 5.1.7 on 2025-03-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
